pidFile: "/tmp/ssd.pid"
statistic:
  interval: 60s
webServer:
  host: "127.0.0.1"
  port: 8090
persistence:
  filePath: "/etc/ssd/data.bin"
  saveInterval: 600s
cache:
  enabled: true
  size: 32
metrics:
  enabled: true
logger:
  level: "info"
  mode: 0640
  dir: "/var/log/ssd"
