pidFile: "/tmp/ssd.pid"
statistic:
  interval: 60s
webServer:
  host: "0.0.0.0"
  port: 8090
persistence:
  filePath: "/data/ssd/data.bin"
  saveInterval: 120s
logger:
  level: "info"
  mode: 0640
  dir: "/var/log/ssd"
